spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false

server.servlet.session.persistent=true
server.servlet.session.store-dir=./target/sessions

logging.level.org.hibernate.orm.service=ERROR

spring.datasource.url=jdbc:postgresql://localhost:5432/accidents
spring.datasource.username=devvk
spring.datasource.password=

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
